import assert from 'node:assert/strict'
import { _electron as electron } from 'playwright-core'
import { mkdir, copyFile, readFile, writeFile } from 'node:fs/promises'
import { execFileSync } from 'node:child_process'
import { resolve } from 'node:path'

// 全程使用真实 Electron、后端与 GLM；独立数据目录保留实际任务产物。
const directory = resolve('.artifacts', `c11-${Date.now()}`)
const evidence = resolve('../docs/acceptance/assets/C11')
await mkdir(`${directory}/data`, { recursive: true })
await mkdir(evidence, { recursive: true })
await copyFile('../backend/data/config.json', `${directory}/data/config.json`)
const app = await electron.launch({ args: ['.', `--user-data-dir=${directory}`], executablePath: resolve('node_modules/electron/dist/Electron.app/Contents/MacOS/Electron') })
const page = await app.firstWindow()
page.setDefaultTimeout(180000)
const errors = []
page.on('pageerror', (error) => errors.push(error.message))
const output = []
const record = (event, data = {}) => { const row = { event, ...data }; output.push(row); console.log(JSON.stringify(row)) }
const screenshot = async (name) => page.screenshot({ path: `${evidence}/${name}.png` })
const request = (path) => page.evaluate(async (path) => {
  const port = await window.agentcrew.getBackendPort()
  const token = await window.agentcrew.getToken()
  const response = await fetch(`http://127.0.0.1:${port}/api${path}`, { headers: { Authorization: `Bearer ${token}` } })
  if (!response.ok) throw new Error(`HTTP ${response.status}`)
  return (await response.json()).data
}, path)
const current = () => page.evaluate(() => sessionStorage.getItem('conversation'))
const send = async (text, name = '发送任务') => {
  await page.getByRole('textbox', { name: '任务指令', exact: true }).fill(text)
  await page.getByRole('button', { name, exact: true }).click()
}

try {
  await page.getByText('任务服务已连接', { exact: true }).waitFor()
  const composer = page.getByRole('textbox', { name: '任务指令', exact: true })
  await composer.fill('键盘草稿')
  await composer.press('Shift+Enter')
  assert.equal(await composer.inputValue(), '键盘草稿\n')
  await send('请依次使用 write_file 在当前工作目录创建 c11-first.txt（内容为 C11 first），再创建 c11-second.txt（内容为 C11 second），再创建 c11-third.txt（内容为 C11 third）。每次调用完成后再进行下一次调用。最后逐一读取三个文件并回复文件名称和内容。')
  await page.getByRole('button', { name: '允许', exact: true }).waitFor()
  const id = await current()
  await screenshot('approval')
  const before = await page.locator('.message.user').allTextContents()
  await page.reload()
  await page.getByRole('button', { name: '允许', exact: true }).waitFor()
  assert.deepEqual(await page.locator('.message.user').allTextContents(), before)
  await screenshot('refresh-pending')
  record('refresh-restored', { conversation: id, state: await request(`/conversations/${id}/state`) })
  await page.getByRole('button', { name: '允许', exact: true }).click()
  await page.locator('.approval').filter({ hasText: 'c11-first.txt' }).waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: '总是允许', exact: true }).waitFor()
  await screenshot('allow-always')
  await page.getByRole('button', { name: '总是允许', exact: true }).click()
  await page.locator('.message.assistant').waitFor()
  const initialReply = await page.locator('.message.assistant .message-text').textContent()
  await page.waitForFunction(() => document.querySelector('.notice')?.textContent?.includes('· idle'))
  await page.waitForFunction(() => (document.querySelector('.message.assistant .message-text')?.textContent?.length ?? 0) > 50)
  const scope = await request(`/conversations/${id}/scope`)
  for (const [name, content] of [['first', 'C11 first'], ['second', 'C11 second'], ['third', 'C11 third']]) assert.equal((await readFile(`${scope.workspace_dir}/c11-${name}.txt`, 'utf8')).trim(), content)
  const runs = await request(`/conversations/${id}/task-runs`)
  const history = await request(`/task-runs/${runs[0].id}/events?after_seq=0&limit=500`)
  assert.equal(history.items.filter((e) => e.type === 'permission.requested').length, 2)
  assert.ok(history.items.some((e) => e.type === 'tool.completed'))
  const finalReply = history.items.filter((e) => e.type === 'llm.request_done' && e.payload.tool_uses.length === 0).at(-1).payload.text
  assert.ok(initialReply.length < finalReply.length)
  await page.waitForFunction((text) => document.querySelector('.message.assistant .message-text')?.textContent === text, finalReply)
  record('typing-completed', { initialLength: initialReply.length, finalLength: finalReply.length, reply: finalReply })
  await screenshot('completed')
  record('write-approval-completed', { conversation: id, events: history.items.map((e) => ({ global_seq: e.global_seq, type: e.type })), files: ['c11-first.txt', 'c11-second.txt', 'c11-third.txt'] })
  await page.reload()
  await page.locator('.message.assistant').waitFor()
  assert.equal(await page.locator('.message.assistant .message-text').textContent(), finalReply)
  record('completed-history-restored', { characters: finalReply.length })

  await page.getByRole('button', { name: '＋ 新建任务', exact: true }).click()
  await send('必须调用 ask_user 工具向我提问“请提供验收代号”，等待回答后原样回复答案。')
  await page.getByRole('textbox', { name: '问题回答', exact: true }).waitFor()
  const questionId = await current()
  await screenshot('question')
  await page.getByRole('textbox', { name: '问题回答', exact: true }).fill('C11 真人回答')
  await page.getByRole('button', { name: '提交回答', exact: true }).click()
  await page.locator('.message.assistant').waitFor()
  await page.waitForFunction(() => document.querySelector('.notice')?.textContent?.includes('· idle'))
  record('question-answered', { conversation: questionId })

  await page.getByRole('button', { name: '＋ 新建任务', exact: true }).click()
  await send('必须调用 ask_user 工具提问“排队验收等待”，等待我回答。')
  await page.getByRole('textbox', { name: '问题回答', exact: true }).waitFor()
  const queueId = await current()
  await send('必须调用 ask_user 工具提问“队首已继续”，等待回答后回复完成。', '加入队列')
  await send('只回复“剩余指令不应执行”。', '加入队列')
  await page.getByText('排队中 · 2 条', { exact: true }).waitFor()
  await screenshot('queue-two')
  await page.getByRole('button', { name: '停止任务', exact: true }).click()
  await page.getByText('队列已暂停 · 2 条', { exact: true }).waitFor()
  await screenshot('queue-paused')
  await page.getByRole('button', { name: '继续队列', exact: true }).click()
  await page.getByRole('textbox', { name: '问题回答', exact: true }).waitFor()
  await page.getByRole('button', { name: '取消剩余', exact: true }).click()
  await page.getByRole('textbox', { name: '问题回答', exact: true }).fill('完成')
  await page.getByRole('button', { name: '提交回答', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.notice')?.textContent?.includes('· idle'))
  const queueState = await request(`/conversations/${queueId}/state`)
  assert.equal(queueState.queue.length, 0)
  assert.equal((await request(`/conversations/${queueId}/task-runs`)).length, 2)
  assert.equal(await page.locator('.message.user').count(), 3)
  await screenshot('queue-completed')
  record('queue-chain-completed', { conversation: queueId, state: queueState })

  const oldPort = await page.evaluate(() => window.agentcrew.getBackendPort())
  const processLine = execFileSync('ps', ['-axo', 'pid,command'], { encoding: 'utf8' }).split('\n').find((line) => line.includes('/python3 -m agentcrew_server') && line.includes(directory))
  assert.ok(processLine)
  const pid = Number(processLine.trim().split(/\s+/)[0])
  process.kill(pid, 'SIGKILL')
  await page.waitForFunction(async (oldPort) => { const port = await window.agentcrew.getBackendPort(); return port && port !== oldPort }, oldPort)
  await page.waitForFunction(() => document.querySelector('.notice')?.textContent?.includes('已连接'))
  assert.equal(await page.locator('.message.user').count(), 3)
  await screenshot('sidecar-reconnected')
  record('sidecar-reconnected', { killedPid: pid, oldPort, newPort: await page.evaluate(() => window.agentcrew.getBackendPort()) })
  await page.reload()
  await page.waitForFunction(() => document.querySelectorAll('.message.user').length === 3)
  assert.deepEqual(await request(`/conversations/${queueId}/state`), queueState)

  const imported = await page.evaluate(async ({ file, directory }) => {
    const port = await window.agentcrew.getBackendPort()
    const token = await window.agentcrew.getToken()
    const response = await fetch(`http://127.0.0.1:${port}/api/conversations`, {
      method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ instruction: '请只回复“材料验收完成”。', import_files: [file, `${directory}/不存在的文件.txt`], folders: [directory] })
    })
    if (!response.ok) throw new Error(`HTTP ${response.status}`)
    return (await response.json()).data
  }, { file: resolve('package.json'), directory })
  assert.equal(imported.materials[0].error, null)
  assert.ok(imported.materials[1].error)
  assert.equal(await readFile(`${imported.scope.materials_dir}/package.json`, 'utf8'), await readFile('package.json', 'utf8'))
  await page.reload()
  await page.locator('.recent-tasks button').first().click()
  await page.getByText(/导入失败：/).waitFor()
  await page.locator('.message.assistant').waitFor()
  await screenshot('materials-partial-error')
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(900, 760))
  await page.getByRole('button', { name: '展开运行详情', exact: true }).click()
  await page.getByText(/导入失败：/).waitFor()
  await screenshot('narrow-details')
  await page.keyboard.press('Escape')
  assert.equal(await page.locator('#run-details').count(), 0)
  record('materials-and-narrow-passed', { materials: imported.materials, scope: imported.scope })
  assert.deepEqual(errors, [])
  record('all-checks-passed', { directory })
} finally {
  await writeFile(`${evidence}/real-output.json`, JSON.stringify(output, null, 2))
  await screenshot('last-state')
  await app.close()
}
